version: "3.8"
services:
  Homework-03:
    image: gigliomaniac1/domsnaketest:latest
    build: .
    container_name: Homework03-1
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
