version: "3.8"
services:
  Homework-03:
    image: gigliomaniac1/homework03:latest
    build: .
    container_name: Homework03
    ports:
      - "80:3700"
    environment:
      - PORT=3700
    volumes:
      - ./:/app
    command: ["node", "index.js"]
